### ISSUE TITLE
Installing pcl-py 0.2.11 failed

### ISSUE THREAD

**Issue by chenmingjiong** [cmpute/pcl.py#12]
Ubuntu 18.04.3 LTS
Python 3.8.12 (conda)
Cython 0.29.24
Installing using `pip install pcl-py`

```
Building wheels for collected packages: pcl-py
  Building wheel for pcl-py (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/chenmingrui/anaconda3/envs/droidenv/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-agoqmaus/pcl-py_42320a6459424cc99fa78d2ba2f502cd/setup.py'"'"'; __file__='"'"'/tmp/pip-install-agoqmaus/pcl-py_42320a6459424cc99fa78d2ba2f502cd/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-5jqzh6ts
       cwd: /tmp/pip-install-agoqmaus/pcl-py_42320a6459424cc99fa78d2ba2f502cd/
  Complete output (91 lines):


  --------------------------------------------------------------------------------
  -- Trying "Ninja" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  -- The C compiler identification is GNU 7.4.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- The CXX compiler identification is GNU 7.4.0
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-install-agoqmaus/pcl-py_42320a6459424cc99fa78d2ba2f502cd/_cmake_test_compile/build
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja" generator - success
  --------------------------------------------------------------------------------

  Configuring Project
    Working directory:
      /tmp/pip-install-agoqmaus/pcl-py_42320a6459424cc99fa78d2ba2f502cd/_skbuild/linux-x86_64-3.8/cmake-build
    Command:
      cmake /tmp/pip-install-agoqmaus/pcl-py_42320a6459424cc99fa78d2ba2f502cd -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-agoqmaus/pcl-py_42320a6459424cc99fa78d2ba2f502cd/_skbuild/linux-x86_64-3.8/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/home/chenmingrui/anaconda3/envs/droidenv/bin/python3.8 -DPYTHON_VERSION_STRING:STRING=3.8.12 -DPYTHON_INCLUDE_DIR:PATH=/home/chenmingrui/anaconda3/envs/droidenv/include/python3.8 -DPYTHON_LIBRARY:FILEPATH=/home/chenmingrui/anaconda3/envs/droidenv/lib/libpython3.8.so -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/home/chenmingrui/anaconda3/envs/droidenv/lib/python3.8/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release

  -- The C compiler identification is GNU 7.4.0
  -- The CXX compiler identification is GNU 7.4.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found PythonInterp: /home/chenmingrui/anaconda3/envs/droidenv/bin/python3.8 (found version "3.8.12")
  -- Found PythonLibs: /home/chenmingrui/anaconda3/envs/droidenv/lib/libpython3.8.so (found version "3.8.12")
  -- Found Cython: /home/chenmingrui/anaconda3/envs/droidenv/bin/cython
  -- Found NumPy: /home/chenmingrui/anaconda3/envs/droidenv/lib/python3.8/site-packages/numpy/core/include (found version "1.21.2")
  CMake Error at pcl/CMakeLists.txt:1 (find_package):
    By not providing "FindPCL.cmake" in CMAKE_MODULE_PATH this project has
    asked CMake to find a package configuration file provided by "PCL", but
    CMake did not find one.

    Could not find a package configuration file provided by "PCL" with any of
    the following names:

      PCLConfig.cmake
      pcl-config.cmake

    Add the installation prefix of "PCL" to CMAKE_PREFIX_PATH or set "PCL_DIR"
    to a directory containing one of the above files.  If "PCL" provides a
    separate development package or SDK, be sure it has been installed.


  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-agoqmaus/pcl-py_42320a6459424cc99fa78d2ba2f502cd/_skbuild/linux-x86_64-3.8/cmake-build/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "/home/chenmingrui/anaconda3/envs/droidenv/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 586, in setup
      env = cmkr.configure(cmake_args,
    File "/home/chenmingrui/anaconda3/envs/droidenv/lib/python3.8/site-packages/skbuild/cmaker.py", line 237, in configure
      raise SKBuildError(

  An error occurred while configuring with CMake.
    Command:
      cmake /tmp/pip-install-agoqmaus/pcl-py_42320a6459424cc99fa78d2ba2f502cd -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-agoqmaus/pcl-py_42320a6459424cc99fa78d2ba2f502cd/_skbuild/linux-x86_64-3.8/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/home/chenmingrui/anaconda3/envs/droidenv/bin/python3.8 -DPYTHON_VERSION_STRING:STRING=3.8.12 -DPYTHON_INCLUDE_DIR:PATH=/home/chenmingrui/anaconda3/envs/droidenv/include/python3.8 -DPYTHON_LIBRARY:FILEPATH=/home/chenmingrui/anaconda3/envs/droidenv/lib/libpython3.8.so -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/home/chenmingrui/anaconda3/envs/droidenv/lib/python3.8/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release
    Source directory:
      /tmp/pip-install-agoqmaus/pcl-py_42320a6459424cc99fa78d2ba2f502cd
    Working directory:
      /tmp/pip-install-agoqmaus/pcl-py_42320a6459424cc99fa78d2ba2f502cd/_skbuild/linux-x86_64-3.8/cmake-build
  Please see CMake's output for more information.
  ----------------------------------------
  ERROR: Failed building wheel for pcl-py
  Running setup.py clean for pcl-py
Failed to build pcl-py
Installing collected packages: pcl-py
    Running setup.py install for pcl-py ... error
    ERROR: Command errored out with exit status 1:
     command: /home/chenmingrui/anaconda3/envs/droidenv/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-agoqmaus/pcl-py_42320a6459424cc99fa78d2ba2f502cd/setup.py'"'"'; __file__='"'"'/tmp/pip-install-agoqmaus/pcl-py_42320a6459424cc99fa78d2ba2f502cd/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7_6eqead/install-record.txt --single-version-externally-managed --compile --install-headers /home/chenmingrui/anaconda3/envs/droidenv/include/python3.8/pcl-py
         cwd: /tmp/pip-install-agoqmaus/pcl-py_42320a6459424cc99fa78d2ba2f502cd/
    Complete output (91 lines):


    --------------------------------------------------------------------------------
    -- Trying "Ninja" generator
    --------------------------------
    ---------------------------
    ----------------------
    -----------------
    ------------
    -------
    --
    Not searching for unused variables given on the command line.
    -- The C compiler identification is GNU 7.4.0
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- The CXX compiler identification is GNU 7.4.0
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-install-agoqmaus/pcl-py_42320a6459424cc99fa78d2ba2f502cd/_cmake_test_compile/build
    --
    -------
    ------------
    -----------------
    ----------------------
    ---------------------------
    --------------------------------
    -- Trying "Ninja" generator - success
    --------------------------------------------------------------------------------

    Configuring Project
      Working directory:
        /tmp/pip-install-agoqmaus/pcl-py_42320a6459424cc99fa78d2ba2f502cd/_skbuild/linux-x86_64-3.8/cmake-build
      Command:
        cmake /tmp/pip-install-agoqmaus/pcl-py_42320a6459424cc99fa78d2ba2f502cd -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-agoqmaus/pcl-py_42320a6459424cc99fa78d2ba2f502cd/_skbuild/linux-x86_64-3.8/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/home/chenmingrui/anaconda3/envs/droidenv/bin/python3.8 -DPYTHON_VERSION_STRING:STRING=3.8.12 -DPYTHON_INCLUDE_DIR:PATH=/home/chenmingrui/anaconda3/envs/droidenv/include/python3.8 -DPYTHON_LIBRARY:FILEPATH=/home/chenmingrui/anaconda3/envs/droidenv/lib/libpython3.8.so -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/home/chenmingrui/anaconda3/envs/droidenv/lib/python3.8/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release

    -- The C compiler identification is GNU 7.4.0
    -- The CXX compiler identification is GNU 7.4.0
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found PythonInterp: /home/chenmingrui/anaconda3/envs/droidenv/bin/python3.8 (found version "3.8.12")
    -- Found PythonLibs: /home/chenmingrui/anaconda3/envs/droidenv/lib/libpython3.8.so (found version "3.8.12")
    -- Found Cython: /home/chenmingrui/anaconda3/envs/droidenv/bin/cython
    -- Found NumPy: /home/chenmingrui/anaconda3/envs/droidenv/lib/python3.8/site-packages/numpy/core/include (found version "1.21.2")
    CMake Error at pcl/CMakeLists.txt:1 (find_package):
      By not providing "FindPCL.cmake" in CMAKE_MODULE_PATH this project has
      asked CMake to find a package configuration file provided by "PCL", but
      CMake did not find one.

      Could not find a package configuration file provided by "PCL" with any of
      the following names:

        PCLConfig.cmake
        pcl-config.cmake

      Add the installation prefix of "PCL" to CMAKE_PREFIX_PATH or set "PCL_DIR"
      to a directory containing one of the above files.  If "PCL" provides a
      separate development package or SDK, be sure it has been installed.


    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-install-agoqmaus/pcl-py_42320a6459424cc99fa78d2ba2f502cd/_skbuild/linux-x86_64-3.8/cmake-build/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "/home/chenmingrui/anaconda3/envs/droidenv/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 586, in setup
        env = cmkr.configure(cmake_args,
      File "/home/chenmingrui/anaconda3/envs/droidenv/lib/python3.8/site-packages/skbuild/cmaker.py", line 237, in configure
        raise SKBuildError(

    An error occurred while configuring with CMake.
      Command:
        cmake /tmp/pip-install-agoqmaus/pcl-py_42320a6459424cc99fa78d2ba2f502cd -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-agoqmaus/pcl-py_42320a6459424cc99fa78d2ba2f502cd/_skbuild/linux-x86_64-3.8/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/home/chenmingrui/anaconda3/envs/droidenv/bin/python3.8 -DPYTHON_VERSION_STRING:STRING=3.8.12 -DPYTHON_INCLUDE_DIR:PATH=/home/chenmingrui/anaconda3/envs/droidenv/include/python3.8 -DPYTHON_LIBRARY:FILEPATH=/home/chenmingrui/anaconda3/envs/droidenv/lib/libpython3.8.so -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/home/chenmingrui/anaconda3/envs/droidenv/lib/python3.8/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release
      Source directory:
        /tmp/pip-install-agoqmaus/pcl-py_42320a6459424cc99fa78d2ba2f502cd
      Working directory:
        /tmp/pip-install-agoqmaus/pcl-py_42320a6459424cc99fa78d2ba2f502cd/_skbuild/linux-x86_64-3.8/cmake-build
    Please see CMake's output for more information.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/chenmingrui/anaconda3/envs/droidenv/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-agoqmaus/pcl-py_42320a6459424cc99fa78d2ba2f502cd/setup.py'"'"'; __file__='"'"'/tmp/pip-install-agoqmaus/pcl-py_42320a6459424cc99fa78d2ba2f502cd/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7_6eqead/install-record.txt --single-version-externally-managed --compile --install-headers /home/chenmingrui/anaconda3/envs/droidenv/include/python3.8/pcl-py Check the logs for full command output.
```

**Comment by chenmingjiongjiong** [comment]
Thanks. Problem solved.
