### ISSUE TITLE
Error compiling Cython file

### ISSUE THREAD

**Issue by AlcatrAAz** [cmpute/pcl.py#17]
Hello

I got an error when I try to install pcl.py via pip or manually. I'm on Ubuntu 18. I think this is the main error:

```
Error compiling Cython file:
    ------------------------------------------------------------
    ...
        property InputCloud:
            def __get__(self):
                return self._input
            def __set__(self, PointCloud inputc):
                self._input = inputc
                self._ptr.get().setInputCloud(inputc.csptr())
                                                         ^
    ------------------------------------------------------------
    
    /tmp/pip-install-ow0bofk1/pcl-py_f22239df09f5481b8d1ddba3fbdb4573/pcl/common/PCLBase.pyx:15:54: Cannot assign type 'shared_ptr[const PCLPointCloud2]' to 'PCLPointCloud2ConstPtr'
```
And it can't find the VTK apparently but the files are there in `/usr/lib/cmake/vtk-6.3`..
Here is the complete error (unfortunately I can't paste it completely because the message is too long, but I removed only unrelevant infos): 

<details>

```

lg@lg-ThinkPad-P52:~$ pip3 install pcl-py
Defaulting to user installation because normal site-packages is not writeable
Collecting pcl-py
  Using cached pcl-py-0.2.11.tar.gz (291 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.11 in ./.local/lib/python3.6/site-packages (from pcl-py) (1.19.1)
Building wheels for collected packages: pcl-py
  Building wheel for pcl-py (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-cg42ieyg
       cwd: /tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/
  Complete output (855 lines):
  
  
  --------------------------------------------------------------------------------
  -- Trying "Ninja" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  -- The C compiler identification is GNU 7.5.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- The CXX compiler identification is GNU 7.5.0
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/_cmake_test_compile/build
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja" generator - success
  --------------------------------------------------------------------------------
  
  Configuring Project
    Working directory:
      /tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/_skbuild/linux-x86_64-3.6/cmake-build
    Command:
      cmake /tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/_skbuild/linux-x86_64-3.6/cmake-install -DPYTHON_VERSION_STRING:STRING=3.6.9 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/home/lg/.local/lib/python3.6/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/usr/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.6m -DPYTHON_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.6m.so -DPython_EXECUTABLE:PATH=/usr/bin/python3 -DPython_ROOT_DIR:PATH=/usr -DPython_INCLUDE_DIR:PATH=/usr/include/python3.6m -DPython_FIND_REGISTRY:STRING=NEVER -DPython_NumPy_INCLUDE_DIRS:PATH=/home/lg/.local/lib/python3.6/site-packages/numpy/core/include -DPython3_EXECUTABLE:PATH=/usr/bin/python3 -DPython3_ROOT_DIR:PATH=/usr -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.6m -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_NumPy_INCLUDE_DIRS:PATH=/home/lg/.local/lib/python3.6/site-packages/numpy/core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=/home/lg/.local/lib/python3.6/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release
  
  -- The C compiler identification is GNU 7.5.0
  -- The CXX compiler identification is GNU 7.5.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found PythonInterp: /usr/bin/python3 (found version "3.6.9")
  -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.9")
  -- Found Cython: /usr/bin/cython
  -- Found NumPy: /usr/include (found version "1.19.1")
  -- Checking for module 'eigen3'
  --   Found eigen3, version 3.3.4
  CMake Warning (dev) at /home/lg/.local/lib/python3.6/site-packages/cmake/data/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
    The package name passed to `find_package_handle_standard_args` (eigen) does
    not match the name of the calling package (PCL).  This can lead to problems
    in calling code that expects `find_package` result variables (e.g.,
    `_FOUND`) to follow a certain pattern.
  Call Stack (most recent call first):
    /usr/lib/x86_64-linux-gnu/cmake/pcl/PCLConfig.cmake:153 (find_package_handle_standard_args)
    /usr/lib/x86_64-linux-gnu/cmake/pcl/PCLConfig.cmake:638 (find_eigen)
    /usr/lib/x86_64-linux-gnu/cmake/pcl/PCLConfig.cmake:850 (find_external_library)
    pcl/CMakeLists.txt:1 (find_package)
  This warning is for project developers.  Use -Wno-dev to suppress it.
  
  -- Found eigen: /usr/include/eigen3
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - found
  -- Found Threads: TRUE
  -- Found Boost: /usr/include (found suitable version "1.65.1", minimum required is "1.40.0") found components: system filesystem thread date_time iostreams serialization chrono atomic regex
  -- looking for PCL_COMMON
  CMake Warning (dev) at /home/lg/.local/lib/python3.6/site-packages/cmake/data/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
    The package name passed to `find_package_handle_standard_args` (PCL_COMMON)
    does not match the name of the calling package (PCL).  This can lead to
    problems in calling code that expects `find_package` result variables
    (e.g., `_FOUND`) to follow a certain pattern.
  Call Stack (most recent call first):
    /usr/lib/x86_64-linux-gnu/cmake/pcl/PCLConfig.cmake:911 (find_package_handle_standard_args)
    pcl/CMakeLists.txt:1 (find_package)
  This warning is for project developers.  Use -Wno-dev to suppress it.

  
  -- Could NOT find DSSDK (missing: _DSSDK_LIBRARIES)
  ** WARNING ** io features related to dssdk will be disabled
  ** WARNING ** io features related to pcap will be disabled
  ** WARNING ** io features related to png will be disabled
  -- The imported target "vtkRenderingPythonTkWidgets" references the file
     "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
  but this file does not exist.  Possible reasons include:
  * The file was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and contained
     "/usr/lib/cmake/vtk-6.3/VTKTargets.cmake"
  but not all the files it references.
  
  -- The imported target "vtk" references the file
     "/usr/bin/vtk"
  but this file does not exist.  Possible reasons include:
  * The file was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and contained
     "/usr/lib/cmake/vtk-6.3/VTKTargets.cmake"
  but not all the files it references.
  

  
  -- Could NOT find DSSDK (missing: _DSSDK_LIBRARIES)
  ** WARNING ** io features related to dssdk will be disabled
  ** WARNING ** io features related to pcap will be disabled
  ** WARNING ** io features related to png will be disabled
  -- The imported target "vtkRenderingPythonTkWidgets" references the file
     "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
  but this file does not exist.  Possible reasons include:
  * The file was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and contained
     "/usr/lib/cmake/vtk-6.3/VTKTargets.cmake"
  but not all the files it references.
  
  -- The imported target "vtk" references the file
     "/usr/bin/vtk"
  but this file does not exist.  Possible reasons include:
  * The file was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and contained
     "/usr/lib/cmake/vtk-6.3/VTKTargets.cmake"
  but not all the files it references.

  -- PCL visualization found, build pcl.visualization
  _modinit_prefix:PyInit_
  _modinit_prefix:PyInit_
  -- Configuring done
  -- Generating done
  CMake Warning:
    Manually-specified variables were not used by the project:
  
      Python3_EXECUTABLE
      Python3_FIND_REGISTRY
      Python3_INCLUDE_DIR
      Python3_NumPy_INCLUDE_DIRS
      Python3_ROOT_DIR
      Python_FIND_REGISTRY
      Python_INCLUDE_DIR
      Python_NumPy_INCLUDE_DIRS
      Python_ROOT_DIR
      SKBUILD
  
  
  -- Build files have been written to: /tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/_skbuild/linux-x86_64-3.6/cmake-build
  [1/22] Generating CXX source pcl/visualization/_connection.cxx
  [2/22] Generating CXX source pcl/common/PCLBase.cxx
  FAILED: pcl/common/PCLBase.cxx /tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/_skbuild/linux-x86_64-3.6/cmake-build/pcl/common/PCLBase.cxx
  cd /tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/_skbuild/linux-x86_64-3.6/cmake-build/pcl/common && /usr/bin/cython --cplus --include-dir /usr/include/python3.6m --include-dir /usr/include --include-dir /usr/include/pcl-1.8 --include-dir /usr/include/eigen3 --include-dir /tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/_skbuild/linux-x86_64-3.6/cmake-build/pcl/include --include-dir /tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/pcl/include /tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/pcl/common/PCLBase.pyx --output-file /tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/_skbuild/linux-x86_64-3.6/cmake-build/pcl/common/PCLBase.cxx
  
  Error compiling Cython file:
  ------------------------------------------------------------
  ...
      property InputCloud:
          def __get__(self):
              return self._input
          def __set__(self, PointCloud inputc):
              self._input = inputc
              self._ptr.get().setInputCloud(inputc.csptr())
                                                       ^
  ------------------------------------------------------------
  
  /tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/pcl/common/PCLBase.pyx:15:54: Cannot assign type 'shared_ptr[const PCLPointCloud2]' to 'PCLPointCloud2ConstPtr'
  [3/22] Generating CXX source pcl/io/_io.cxx
  [4/22] Generating CXX source pcl/filters/_filters.cxx
  [5/22] Generating CXX source pcl/PointField.cxx
  [6/22] Building CXX object pcl/visualization/CMakeFiles/_connection.dir/_connection.cxx.o
  [7/22] Generating CXX source pcl/PointCloud.cxx
  ninja: build stopped: subcommand failed.
  Traceback (most recent call last):
    File "/home/lg/.local/lib/python3.6/site-packages/skbuild/setuptools_wrap.py", line 640, in setup
      cmkr.make(make_args, install_target=cmake_install_target, env=env)
    File "/home/lg/.local/lib/python3.6/site-packages/skbuild/cmaker.py", line 672, in make
      self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
    File "/home/lg/.local/lib/python3.6/site-packages/skbuild/cmaker.py", line 704, in make_impl
      "An error occurred while building with CMake.\n"
  
  An error occurred while building with CMake.
    Command:
      cmake --build . --target install --config Release --
    Install target:
      install
    Source directory:
      /tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c
    Working directory:
      /tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/_skbuild/linux-x86_64-3.6/cmake-build
  Please check the install target is valid and see CMake's output for more information.
  ----------------------------------------
  ERROR: Failed building wheel for pcl-py
  Running setup.py clean for pcl-py
Failed to build pcl-py
Installing collected packages: pcl-py
    Running setup.py install for pcl-py ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-dwrweqhd/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/lg/.local/include/python3.6m/pcl-py
         cwd: /tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/
    Complete output (857 lines):
    /home/lg/.local/lib/python3.6/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    
    
    --------------------------------------------------------------------------------
    -- Trying "Ninja" generator
    --------------------------------
    ---------------------------
    ----------------------
    -----------------
    ------------
    -------
    --
    Not searching for unused variables given on the command line.
    -- The C compiler identification is GNU 7.5.0
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- The CXX compiler identification is GNU 7.5.0
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/_cmake_test_compile/build
    --
    -------
    ------------
    -----------------
    ----------------------
    ---------------------------
    --------------------------------
    -- Trying "Ninja" generator - success
    --------------------------------------------------------------------------------
    
    Configuring Project
      Working directory:
        /tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/_skbuild/linux-x86_64-3.6/cmake-build
      Command:
        cmake /tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/_skbuild/linux-x86_64-3.6/cmake-install -DPYTHON_VERSION_STRING:STRING=3.6.9 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/home/lg/.local/lib/python3.6/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/usr/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.6m -DPYTHON_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.6m.so -DPython_EXECUTABLE:PATH=/usr/bin/python3 -DPython_ROOT_DIR:PATH=/usr -DPython_INCLUDE_DIR:PATH=/usr/include/python3.6m -DPython_FIND_REGISTRY:STRING=NEVER -DPython_NumPy_INCLUDE_DIRS:PATH=/home/lg/.local/lib/python3.6/site-packages/numpy/core/include -DPython3_EXECUTABLE:PATH=/usr/bin/python3 -DPython3_ROOT_DIR:PATH=/usr -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.6m -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_NumPy_INCLUDE_DIRS:PATH=/home/lg/.local/lib/python3.6/site-packages/numpy/core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=/home/lg/.local/lib/python3.6/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release
    
    -- The C compiler identification is GNU 7.5.0
    -- The CXX compiler identification is GNU 7.5.0
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found PythonInterp: /usr/bin/python3 (found version "3.6.9")
    -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.9")
    -- Found Cython: /usr/bin/cython
    -- Found NumPy: /usr/include (found version "1.19.1")
    -- Checking for module 'eigen3'
    --   Found eigen3, version 3.3.4
    CMake Warning (dev) at /home/lg/.local/lib/python3.6/site-packages/cmake/data/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
      The package name passed to `find_package_handle_standard_args` (eigen) does
      not match the name of the calling package (PCL).  This can lead to problems
      in calling code that expects `find_package` result variables (e.g.,
      `_FOUND`) to follow a certain pattern.
    Call Stack (most recent call first):
      /usr/lib/x86_64-linux-gnu/cmake/pcl/PCLConfig.cmake:153 (find_package_handle_standard_args)
      /usr/lib/x86_64-linux-gnu/cmake/pcl/PCLConfig.cmake:638 (find_eigen)
      /usr/lib/x86_64-linux-gnu/cmake/pcl/PCLConfig.cmake:850 (find_external_library)
      pcl/CMakeLists.txt:1 (find_package)
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    -- Found eigen: /usr/include/eigen3
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE
    -- Found Boost: /usr/include (found suitable version "1.65.1", minimum required is "1.40.0") found components: system filesystem thread date_time iostreams serialization chrono atomic regex
    -- looking for PCL_COMMON
    CMake Warning (dev) at /home/lg/.local/lib/python3.6/site-packages/cmake/data/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
      The package name passed to `find_package_handle_standard_args` (PCL_COMMON)
      does not match the name of the calling package (PCL).  This can lead to
      problems in calling code that expects `find_package` result variables
      (e.g., `_FOUND`) to follow a certain pattern.
    Call Stack (most recent call first):
      /usr/lib/x86_64-linux-gnu/cmake/pcl/PCLConfig.cmake:911 (find_package_handle_standard_args)
      pcl/CMakeLists.txt:1 (find_package)
    This warning is for project developers.  Use -Wno-dev to suppress it.
    

    
    -- Could NOT find DSSDK (missing: _DSSDK_LIBRARIES)
    ** WARNING ** io features related to dssdk will be disabled
    ** WARNING ** io features related to pcap will be disabled
    ** WARNING ** io features related to png will be disabled
    -- The imported target "vtkRenderingPythonTkWidgets" references the file
       "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
    but this file does not exist.  Possible reasons include:
    * The file was deleted, renamed, or moved to another location.
    * An install or uninstall procedure did not complete successfully.
    * The installation package was faulty and contained
       "/usr/lib/cmake/vtk-6.3/VTKTargets.cmake"
    but not all the files it references.
    
    -- The imported target "vtk" references the file
       "/usr/bin/vtk"
    but this file does not exist.  Possible reasons include:
    * The file was deleted, renamed, or moved to another location.
    * An install or uninstall procedure did not complete successfully.
    * The installation package was faulty and contained
       "/usr/lib/cmake/vtk-6.3/VTKTargets.cmake"
    but not all the files it references.
    
 
    
    -- Could NOT find DSSDK (missing: _DSSDK_LIBRARIES)
    ** WARNING ** io features related to dssdk will be disabled
    ** WARNING ** io features related to pcap will be disabled
    ** WARNING ** io features related to png will be disabled
    -- The imported target "vtkRenderingPythonTkWidgets" references the file
       "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
    but this file does not exist.  Possible reasons include:
    * The file was deleted, renamed, or moved to another location.
    * An install or uninstall procedure did not complete successfully.
    * The installation package was faulty and contained
       "/usr/lib/cmake/vtk-6.3/VTKTargets.cmake"
    but not all the files it references.
    
    -- The imported target "vtk" references the file
       "/usr/bin/vtk"
    but this file does not exist.  Possible reasons include:
    * The file was deleted, renamed, or moved to another location.
    * An install or uninstall procedure did not complete successfully.
    * The installation package was faulty and contained
       "/usr/lib/cmake/vtk-6.3/VTKTargets.cmake"
    but not all the files it references.
    

    -- PCL visualization found, build pcl.visualization
    _modinit_prefix:PyInit_
    _modinit_prefix:PyInit_
    -- Configuring done
    -- Generating done
    CMake Warning:
      Manually-specified variables were not used by the project:
    
        Python3_EXECUTABLE
        Python3_FIND_REGISTRY
        Python3_INCLUDE_DIR
        Python3_NumPy_INCLUDE_DIRS
        Python3_ROOT_DIR
        Python_FIND_REGISTRY
        Python_INCLUDE_DIR
        Python_NumPy_INCLUDE_DIRS
        Python_ROOT_DIR
        SKBUILD
    
    
    -- Build files have been written to: /tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/_skbuild/linux-x86_64-3.6/cmake-build
    [1/22] Generating CXX source pcl/visualization/_connection.cxx
    [2/22] Generating CXX source pcl/common/PCLBase.cxx
    FAILED: pcl/common/PCLBase.cxx /tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/_skbuild/linux-x86_64-3.6/cmake-build/pcl/common/PCLBase.cxx
    cd /tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/_skbuild/linux-x86_64-3.6/cmake-build/pcl/common && /usr/bin/cython --cplus --include-dir /usr/include/python3.6m --include-dir /usr/include --include-dir /usr/include/pcl-1.8 --include-dir /usr/include/eigen3 --include-dir /tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/_skbuild/linux-x86_64-3.6/cmake-build/pcl/include --include-dir /tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/pcl/include /tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/pcl/common/PCLBase.pyx --output-file /tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/_skbuild/linux-x86_64-3.6/cmake-build/pcl/common/PCLBase.cxx
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        property InputCloud:
            def __get__(self):
                return self._input
            def __set__(self, PointCloud inputc):
                self._input = inputc
                self._ptr.get().setInputCloud(inputc.csptr())
                                                         ^
    ------------------------------------------------------------
    
    /tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/pcl/common/PCLBase.pyx:15:54: Cannot assign type 'shared_ptr[const PCLPointCloud2]' to 'PCLPointCloud2ConstPtr'
    [3/22] Generating CXX source pcl/io/_io.cxx
    [4/22] Generating CXX source pcl/filters/_filters.cxx
    [5/22] Generating CXX source pcl/PointField.cxx
    [6/22] Generating CXX source pcl/PointCloud.cxx
    [7/22] Building CXX object pcl/visualization/CMakeFiles/_connection.dir/_connection.cxx.o
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/home/lg/.local/lib/python3.6/site-packages/skbuild/setuptools_wrap.py", line 640, in setup
        cmkr.make(make_args, install_target=cmake_install_target, env=env)
      File "/home/lg/.local/lib/python3.6/site-packages/skbuild/cmaker.py", line 672, in make
        self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
      File "/home/lg/.local/lib/python3.6/site-packages/skbuild/cmaker.py", line 704, in make_impl
        "An error occurred while building with CMake.\n"
    
    An error occurred while building with CMake.
      Command:
        cmake --build . --target install --config Release --
      Install target:
        install
      Source directory:
        /tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c
      Working directory:
        /tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/_skbuild/linux-x86_64-3.6/cmake-build
    Please check the install target is valid and see CMake's output for more information.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1hi13jqz/pcl-py_71924a69a9464d14b2df34c496bfe78c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-dwrweqhd/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/lg/.local/include/python3.6m/pcl-py Check the logs for full command output.
lg@lg-ThinkPad-P52:~$
```
</details>

I hope someone can help and if you need more informations, please say it.

Thanks in advance.

**Comment by cmpute** [comment]
Could you try updating Cython to the latest version?

**Comment by AlcatrAAz** [comment]
Hey

thanks for the fast answer. I think I'm already at the latest version.

```
lg@lg-ThinkPad-P52:~$ pip3 install Cython
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: Cython in ./.local/lib/python3.6/site-packages (0.29.32)

```

**Comment by cmpute** [comment]
Thanks, could you please share your platform? (OS, python vesion, PCL version, etc)

**Comment by AlcatrAAz** [comment]
Yes for sure:

OS = Ubuntu 18.04.6

lg@lg-ThinkPad-P52:/Downloads/pcl.py-master$ python -V
Python 2.7.17
lg@lg-ThinkPad-P52:/Downloads/pcl.py-master$ python3 -V
Python 3.6.9

PCL = 1.8.1

------------------------------------------------

Maybe I found the problem but I don't now how to solve it as I'm not so experienced in cmake.

I found a similar problem [here](https://github.com/cmpute/pcl.py/issues/16)

I completely reinstalled cython via `pip install cython`. I installed it manually via  `sudo python3 setup.py install` and got these last messages:

```
creating /usr/local/lib/python3.6/dist-packages/Cython-0.29.32-py3.6-linux-x86_64.egg
Extracting Cython-0.29.32-py3.6-linux-x86_64.egg to /usr/local/lib/python3.6/dist-packages
Adding Cython 0.29.32 to easy-install.pth file
Installing cygdb script to /usr/local/bin
Installing cython script to /usr/local/bin
Installing cythonize script to /usr/local/bin

Installed /usr/local/lib/python3.6/dist-packages/Cython-0.29.32-py3.6-linux-x86_64.egg
Processing dependencies for Cython==0.29.32
Finished processing dependencies for Cython==0.29.32
```

But in Synaptic Manager I see that I have a cython version (apt version) installed which is (0.26.1-0.4) which seems in `usr/bin/cython`.

I see also when I try to build pcl.py that it finds cython in `usr/bin/cython` which is I think the old version. In `/usr/local/bin` it is definitely the new version.

I don't want to remove the old cython version because it would remove completely ROS and other packages.

Can this be the problem and how can I set it up so that it takes the latest Cython version when I try to build pcl.py?

**Comment by cmpute** [comment]
Hmm the error message is likely indicating that the cython version used is too old. Could you please add a `print(cython.__version__)` line to the setup.py of pcl.py? That should tell the actual version being used

**Comment by cmpute** [comment]
I guess the best solution will be use some kind of virtualenv or conda environment, using newer Cython is mandatory for this library, so you have to make the Python intepreter to find the correct cython instance, which is tedious without virtualenv or conda.

**Comment by cmpute** [comment]
[This is the FindCython file](https://github.com/scikit-build/scikit-build/blob/master/skbuild/resources/cmake/FindCython.cmake). I haven't dig into that file deeply, but I think maybe it's finding the `usr/bin/cython` binary (which I guess is based on Python 2)? Can you try install the scikit-build and cython for python2 (using the `--user` flag to install under the home directory), and then build with python2?

**Comment by AlcatrAAz** [comment]
Hey

okay I managed to get it working now. The Problem was that the `FindCython.cmake` file found the Cython in `usr/bin/cython` which was the old version. 

I set the path "hardcoded" to the new version. I know it is not the best solution but it works now.

In the `FindCython.cmake`
```
if(CYTHON_EXECUTABLE)
  set(CYTHON_EXECUTABLE "/usr/local/bin/cython")
  set(CYTHON_version_command ${CYTHON_EXECUTABLE} --version)
  MESSAGE(${CYTHON_version_command})
  MESSAGE(${CYTHON_EXECUTABLE})
  execute_process(COMMAND ${CYTHON_version_command}
                  OUTPUT_VARIABLE CYTHON_version_output
                  ERROR_VARIABLE CYTHON_version_error
                  RESULT_VARIABLE CYTHON_version_result
                  OUTPUT_STRIP_TRAILING_WHITESPACE
                  ERROR_STRIP_TRAILING_WHITESPACE)
```

I managed to get my script working and I can generate pcd files via python with custom fields.

So thanks for your help and your package!

**Comment by cmpute** [comment]
Glad to hear that! This should be an issue for the `scikit-build` library, you can post an issue there if you would like to fix it in future.
